### ISSUE TITLE
Pas moyen de télécharger l'iso

### ISSUE THREAD

**Issue by Myself-Bloons** [monpremierctf/mon_premier_ctf#2]
Hello,
Vachement intéressé mais pas moyen de DL l'iso au lien suivant :
https://yoloctf.org/yoloctf/iso/yoloctf.ova

Merci pour l'aide !

**Comment by Myself-Bloons** [comment]
Bump

**Comment by jossets** [comment]
L'ova pour virtualbox a été mise à jour et uploadée sur googledrive. 
La documentation a été mise à jour avec le nouveau lien: https://github.com/monpremierctf/mon_premier_ctf/blob/master/doc/install_vm.md
