### ISSUE TITLE
Code invitation invalide

### ISSUE THREAD

**Issue by jason-tonys** [monpremierctf/mon_premier_ctf#3]
Bonjour et merci d'avoir créé une plateforme de ce type,
Cependant j'ai un problème lors de la création de mon compte :
Je tente désespéramment de m'inscrire avec le code **yolo** comme indiqué dans la doc.
Mais le code est invalide, c'est normal ?

Amicalement, Jason GOUZIEN.

**Comment by Myself-Bloons** [comment]
Même chose de mon côté, tu es sur quel site ?

**Comment by jossets** [comment]
Bonjour Jason,


Essayez vous de créer un compte sur http://yoloctf.org ou dans une
VM/serveur ?
Si c'est dans votre VM, le code se trouve dans le fichier ./web_server/.env

# CTF_REGISTER_CODE
#
# Not set or empty : no code needed to register
# CTF_REGISTER_CODE=YOLO

Par défaut, il le code n'est pas activé.


Si c'est sur http://yoloctf.org, je suis preneur d'une description du problème :)

Cordialement,



Sébastien

**Comment by jossets** [comment]
Visiblement, tu as cherché à créer un profil non sur http://yoloctf.org, mais sur http://hacklab.yoloctf.org, sur cette plateforme le code est PT.
J'ai mis le readme à jours du coup :)
