### ISSUE TITLE
Link to zip (and ova) is broken 

### ISSUE THREAD

**Issue by lsignac** [monpremierctf/mon_premier_ctf#4]
<https://yoloctf.org/yoloctf/iso/mon_premier_ctf_install.zip>
==> Error 404

**Comment by Myself-Bloons** [comment]
Same here, would love to test  .ova

**Comment by lsignac** [comment]
Maybe the first challenge is to find the real link ? :)

**Comment by jossets** [comment]
The .ova as been rebuild and uploaded in a googledrive.
The documentation has been updated with the new link: https://github.com/monpremierctf/mon_premier_ctf/blob/master/doc/install_vm.md

Enjoy.

**Comment by lsignac** [comment]
Thank you for updating the ova file.
What about the .zip file ? 
I found the link in the beginning of this document : 
https://github.com/monpremierctf/mon_premier_ctf/blob/master/doc/install_ubuntu.md
